### ISSUE TITLE
Fedora and Ubuntu Kylin icons seem broken

### ISSUE THREAD

**Issue by daPhipz** [quickemu-project/quickemu-icons#1]
When viewing the Fedora and Kylin icons with Gwenview, I can see this:

![Screenshot_2021-10-29_17:14:38](https://user-images.githubusercontent.com/30795174/139460024-26bf71fc-dbd5-43ee-958c-a5daf5f28bff.png)

![Screenshot_2021-10-29_17:13:10](https://user-images.githubusercontent.com/30795174/139460093-844a77ee-89ae-4a2f-9e14-e539429f8313.png)

This is not intentional, is it? :wink:

**Comment by Lukewh** [comment]
Haha, thanks for the report, will take a look 👍

**Comment by daPhipz** [comment]
Weird thing: When I open the Kylin icon in Inkscape, I get this (which seems right to me, but you might wanna check):

![Screenshot_2021-10-29_23:29:06](https://user-images.githubusercontent.com/30795174/139503960-fa79ae44-78f8-4238-bf82-4576e041830b.png)

**Comment by Lukewh** [comment]
The Kylin one is a strange one. Currently it's a PNG embedded in the SVG 🤮! Because I couldn't find an SVG. When I tried to convert it it created many artifacts. I'll try a different method of converting it and see if it helps.

The fedora issue is a strange one, need to look into it some more.
