### ISSUE TITLE
Which ZorinOS icon variant?

### ISSUE THREAD

**Issue by daPhipz** [quickemu-project/quickemu-icons#15]
I came up with these two:
![Screenshot_2021-11-03_18:57:55](https://user-images.githubusercontent.com/30795174/140166142-060e5dfa-48c4-4318-8b53-fbe13b32fea2.png) ![Screenshot_2021-11-03_18:58:16](https://user-images.githubusercontent.com/30795174/140166148-4f6fc85d-8898-4faa-93f4-f97edf618769.png)

Should we absolutely stick with round icons, or is a hexagonal one OK as well? I see that for Fedora, you also ditched the round shape.

**Comment by Lukewh** [comment]
Hexagonal works for me.

Most icons are round, or can be rounded so makes sense to force that shape. As you say Fedora doesn't fit with that and I'm tempted to de-round(word?) The Windows logo too
