### ISSUE TITLE
Request for opinion: Rethink the quickemu overlay

### ISSUE THREAD

**Issue by Lukewh** [quickemu-project/quickemu-icons#49]
My original thoughts behind having the distro icon + the quickemu icon overlay was for use in .desktop files and for running VMs.

It's great that quickqui has implemented the icons, but it's my opinion they don't look great in their current format:
![image](https://user-images.githubusercontent.com/479384/148379543-6afd5e59-1fde-448d-95c1-f14100763a08.png)
 
This is no fault of quickqui, it's an issue with the icons themselves. Used at such a small scale, the quickgui icon becomes noise, and on a dark background, the white circle becomes jarring.

Until there is a way to use these icons for running VMs and .desktop files, I propose we _also_ provide the distro icons *without* the quickemu icon overlay.

*Edit* This may help with situations as described [here](https://github.com/quickemu-project/quickemu-icons/issues/12#issuecomment-1003635483)

**Comment by daPhipz** [comment]
> Used at such a small scale, the quickgui icon becomes noise, and on a dark background, the white circle becomes jarring.

Yeah, I think so too. Additionally, the purpose of the quickgui overlay is to convey the information that this desktop launcher has something to do with Quickgui. Since the icons mentioned above are _inside_ the program itself, this extra info is not necessary.

**Comment by philclifford** [comment]
I think you're right: for quickgui menu use the overlay is too tiny and as daPhipz said somewhat unnecessary .

**Comment by Lukewh** [comment]
I have included the base icons in the build - I believe this can now be closed <3
